init dev
SPuDI-zzz/ToDoListQPD pull request #1
Opened 2023-12-29 09:55 UTC by SPuDI-zzz

2024-01-09 19:53 UTC, Dtroonn requested changes
1) Пока что не вижу redux-toolkit или mobX для хранения состояния глобально (оно тут на самом деле не нужно, но надо изучить одну из этих технологий). 

2) Цвета не вынесены в глобальные css переменные 

3) Пропсы лучше класть рядом с компонентом , а то лень ходить в другую директорию за ними как минимум. (Типо Task.props.ts)

2024-01-09 19:53 UTC, Dtroonn commented on tsconfig.json
> +    "allowJs": true,
Никакого allowJs или он тебе по каким - то причинам где - то нужен ?

2024-01-09 19:53 UTC, Dtroonn commented on src/components/List/List.tsx
> +    );
Не понял зачем тебе дженерик List если честно, чтобы написать на страницах категорий и задач вместо map его, в котором есть этот map  ? Ну если хочешь, то оставь. На мой взгляд - лишняя прослойка и в прод проектах такой бы момент не поняли. Есть кейсы где нужны дженерик компоненты, но этот пока что не тянет

2024-01-09 19:53 UTC, Dtroonn commented on src/components/HeaderNavLink/HeaderNavLink.module.css
> +}
Добавление нужного класса при состоянии активной ссылки выглядело бы лаконичнее чем :global(.active) (см. доку https://reactrouter.com/en/main/components/nav-link )

2024-01-21 20:56 UTC, Dtroonn requested changes
Дополнение: 
1) Нативной валидацией никто не пользуется. Сделать красивую валидацию с отображением текста ошибок под соотв. полем, используя react-hook-form (ну хочешь вручную все это обрабатывай). (про rhf, я писал еще в телеграмме перед проектом) 
2) Нет информации в ui при неуспешных crud операциях (где отображение ошибок  ?) Например при создании и т.д.

2024-01-21 20:56 UTC, Dtroonn commented on src/hooks/useTasks.ts
> +}
Понимаю, что ты хотел сделать, но так обычно с redux не делают, а создают селекторы по доменному имени. Селектор - ф-ия, которая принимает все состояние и  возвращает часть состояния.  Например в твоем случае const selectTasks = () => selectTasksState().tasks (где selectTasksState - тоже селектор, который из стора вытаскивает именно состояние, которое отдается редьюсером, который отвечает за tasks). А далее этот selectTasks просто прокидывается в useSelector и всё. Можешь почитать про селекторы, так же есть библиотека reselect (уже встроена в redux-toolkit), чтобы делать мемоизацию производных значений от состояния, но тут она не особо полезна.

Пишу это только для useTasks. Для остальных подобных хуков дублировать не буду.

2024-01-21 20:56 UTC, Dtroonn commented on src/components/CategoriesPage/CategoriesPage.tsx
> +const CategoriesPage = () => {
Для компонентов страниц обычно создают отдельную папку - pages.

2024-01-21 20:56 UTC, Dtroonn commented on src/components/CategoriesPage/CategoriesPage.tsx
> +]);
Очень странная идея взаимодействовать так с модалками. А если завтра тебе скажут сделать модалку из которой открывается еще одна модалка поверх ? (в текущих условиях это конечно можно будет все равно сделать).  При том если бы ты работал с тем же antd или еще какой-то ui либой, ты бы потерял анимацию закрытия т.к у тебя сразу же возвращается null и происходит немедленный анмаунт из VDOM (AND DOM) . Да и пихать управление модалками в глобальное хранилище тоже задумка не очень, но некоторые так делают, но как мне кажется это не относится к бизнес логике как минимум. А если ты и хотел сделать через глобальный стор, то выбрал бы другой подход  (например описать в сторе состояние каждой модалки). + если бы модалки у тебя бы располагались по-другому, то тебе не пришлось бы например пихать категорию в стейт к модалкам при редактировании, а можно было бы хранить локально в стейте.

2024-01-21 20:56 UTC, Dtroonn commented on src/app/services/api.ts
> +});
А зачем тебе и redux-toolkit-query и созданные слайсы ? Ты должен выбрать что-то одно. У тебя @reduxjs/toolkit/query/react уже сам создает редьюсеры (=> стейт) и т.д . То есть я вообще не понимаю смысла в существовании и слайсов и RTK query вместе.  Из доки: The "API slice" also contains an auto-generated Redux slice reducer and a custom middleware that manages subscription lifetimes. Both of those need to be added to the Redux store: https://redux-toolkit.js.org/rtk-query/overview

2024-01-21 20:56 UTC, Dtroonn commented on src/components/DeleteModal/DeleteModal.tsx
> +
Эта модалка должна называться ConfirmModal по логике (если мыслить абстрактнее и на будущее). + у тебя неправильная декомпозиция попапов/модалок(как минимум много повторений одного и того же кода/стилей в разных модалках) + апи взаимодействия с ними (где тот же проп, который отвечает за открытие/закрытие модалки, например как в mui или antd ? ) Посмотри это видео про декомпозицию попапов, станет проще: https://www.youtube.com/watch?v=20ZVV5ujkFw&t=237s&ab_channel=%D0%90%D0%B9%D0%A2%D0%B8%D0%A1%D0%B8%D0%BD%D1%8F%D0%BA 

Это относится ко всем модалкам на проекте, везде коммент оставлять не буду.

2024-01-21 20:56 UTC, Dtroonn commented on src/components/InputNameModal/InputModal.tsx
> +const InputNameModal:FC<InputNameModalProps> = ({placeholder, value, onChange}) => {
А че название то InputNameModal, а если подумать абстрактнее ? (Этот инпут же может находиться не только в модалке). Это относится ко всем ui-kit компонентам (textarea и т.д). Вообще создай отдельную папку внутри проекта и назови ее ui-kit и сделай эти компоненты абстрактными (представь, что в будущем эту папку могут вынести в отдельный npm пакет и переиспользовать)

2024-01-21 20:56 UTC, Dtroonn commented on src/components/CategoriesPage/CategoriesPage.tsx
> +    const addCategoryHandler = () => setCreateCategoryModal();
Зачем делать addCategoryHandler, если можно просто передать setCreateCategoryModal ?

2024-01-24 17:28 UTC, SPuDI-zzz commented on src/ui-kit/TextAreaWithLabel/TextAreaWithLabel.tsx
> +    useEffect(autoResizeTextArea, [value]);
автоматически увеличивается до определенного размера, если есть гайд, где нормально это делается, буду благодарен

2024-01-29 22:35 UTC, Dtroonn requested changes

2024-01-29 22:35 UTC, Dtroonn commented on src/ui-kit/Button/Button.tsx
> +interface ButtonProps {
Правильный тип для пропов кнопки - экстенд от ``DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>`` + добавление своих нужных пропов (если надо), а далее проброс всех пропов через спред. 

С другими ui-kit компонентами типо форм и т.д должно быть так же. Только обрати внимание на дженерики переданные в интерфейсы/типы

2024-01-29 22:35 UTC, Dtroonn commented on src/ui-kit/ConfirmDialog/ConfirmDialog.tsx
> +    errorMessage?: string;
Здесь по - сути не должно быть errorMessage, ну по крайней мере я бы не стал его сюда пихать + во всех ui-kit либах его обычно нет в модалках. Логичнее сюда сделать проброс кастомного контента тогда через тот же children. Просто с точки зрения логики и зоны ответственности, непонятно каким боком он связан с таким пропом

2024-01-29 22:35 UTC, Dtroonn commented on src/components/ErrorAlert/ErrorAlert.tsx
> +const ErrorAlert:FC<ErrorAlertProps> = ({message, className = ''}) => {
Тогда уж это относится к ui-kit

2024-01-29 22:35 UTC, Dtroonn commented on src/ui-kit/HeaderNavLink/HeaderNavLink.tsx
> +const HeaderNavLink: FC<HeaderNavLinkProps> = ({navigateTo, textLink}) => {
А вот это уже не относится к ui-kit. Оно же явно относится к хэдеру даже по названию + использует react-router-dom т.е если ты захочешь вынести его в отдельный npm пакет, то у тебя появится обязательная зависимость, которая не факт что везде нужна

2024-01-29 22:35 UTC, Dtroonn commented on src/ui-kit/HeaderNavSeparator/HeaderNavSeparator.tsx
> +const HeaderNavSeparator = () => {
Это тож не относится к киту, либо это должно быть просто Separator

2024-01-29 22:35 UTC, Dtroonn commented on src/ui-kit/HeaderNavLink/HeaderNavLink.tsx
> +                }
Кстати, для работы с классами (их мержем/добавлением/удалением хорошо подходит библиотека clsx или classNames, но это не значит что ты щас должен ее затягивать, просто на будущее )

2024-01-29 22:35 UTC, Dtroonn commented on src/ui-kit/Input/Input.tsx
> +    errorMessage,
На самом деле тут должен быть не errorMessage, а helperText т.к у тебя может быть такой же текст под инпутом, как подсказка только не красный. А его окрас будет зависеть от булевого пропа error. Вообще надо делать все максимально абстрактно в ui-kit с расчетом на будущее.

2024-01-29 22:35 UTC, Dtroonn commented on src/ui-kit/ConfirmDialog/ConfirmDialog.tsx
> +import ModalButtonsContainer from '../../components/ModalButtonsContainer/ModalButtonsContainer';
Вынести тогда его в ui-kit т.к у тебя получается странная последовательность зависимостей. У тебя ui-kit зависит от components. что вообще недопустимо. Как ты его вынесешь если что в отдельную либу ? + у тебя получается что кит зависит от components, но components зависят от кит, как то несправедливо получается. Только твой проект должен зависеть от кита, но не иначе. Разверни зависимости

2024-01-29 22:35 UTC, Dtroonn commented on src/ui-kit/TextArea/TextArea.tsx
> +    errorMessage?: string
Аналогичное замечание как и инпуту .

2024-01-29 22:35 UTC, Dtroonn commented on src/ui-kit/MainPopup/MainPopup.tsx
> +import HeaderModal from '../../components/HeaderModal/HeaderModal';
Так же повернуть зависимости.

2024-01-29 22:35 UTC, Dtroonn commented on src/pages/CategoriesPage/CategoriesPage.tsx
> +            {isOpenedCreateCategoryModal && <CreateCategoryModal
При подходе ``isOpenedCreateCategoryModal &&`` , ты потеряешь анимацию закрытия модалки в любом случае, если она есть. Обычно в китах внутри реализуется автоматический анмаут модалки из VDOM=>DOM и регулируется по пропу, но тебе так делать не нужно, просто имей в виду, что такой подход не приветствуется если речь идет об анимации закрытия (а она почти всегда есть )

2024-01-29 22:35 UTC, Dtroonn commented on src/components/CategoryModal/CategoryModal.tsx
> +        }
так можно сделать defaultValues: category

2024-01-29 22:35 UTC, Dtroonn commented on src/components/CategoryModal/CategoryModal.tsx
> +    category: ICategoryRequest;
Вообще на самом деле ты загнал себя немного в ловушку таким способом т.к если полей будет еще больше, то ты будешь для создания прописывать все эти поля по дефолту ? Например 50+ полей. Сделай это опциональным пропом, а defaultValues задавай только если есть category. Да и сам проп надо назвать не category, а initialValues/initialData например или defaultValues

2024-01-29 22:35 UTC, Dtroonn commented on src/components/CreateCategoryModal/CreateCategoryModal.tsx
> +    }
Напишу это здесь один раз. За тебя же useMutation и так все это обрабатывает. Зачем ты это накрутил ? Читать доку https://redux-toolkit.js.org/rtk-query/usage/mutations: 
![image](https://github.com/SPuDI-zzz/ToDoListQPD/assets/61122326/cfc28980-9ede-49da-a9a4-7006d031aaa7)

2024-01-29 22:35 UTC, Dtroonn commented on src/components/Category/Category.tsx
> +export interface TCategoryProps {
Не понял почему называется с T

2024-01-29 22:35 UTC, Dtroonn commented on src/components/Category/Category.tsx
> +            />}
Замечание по условному рендерингу модалок (уже было)

2024-01-29 22:35 UTC, Dtroonn commented on src/interfaces/interfaces.ts
> +export interface ICategory extends ICategoryResponse { }
Я бы вообще сделал только ICategory, не понял смысла этого наследования (только ради следования общему стилю ? ) 

P.S Лучше создавать доменные области для интерфейсов, либо делать каждый интерфейс/тип в своем файле, но в твоем случае пока что позволительно в одном т.к интерфейсов мало и они мелкие

2024-01-29 22:35 UTC, Dtroonn commented on src/interfaces/interfaces.ts
> +}
У тебя по сути таска везде без categoryName и это и есть ITask. а то что ты замапишь и сделаешь это уже ITaskWithCategory как по мне  + тогда тебе не придется делать ITaskResponse и все станет лаконичнее

2024-01-29 22:35 UTC, Dtroonn commented on src/app/services/tasks.api.ts
> +        updateTask: builder.mutation<ITaskResponse, ITaskRequest>({
ITaskRequest - неверный тип для этого кейса т.к в ЗДЕСЬ обязателен id для обновления таски, а он у тебя получается опциональный. Надо разрулить этот момент.  
P.S тасок тоже касается

2024-02-06 22:29 UTC, Dtroonn requested changes
Замечание: 
Не обработано отображение создания/редактирования такски/категорий в формах, нужно чтобы улучшить ux (например лоадер на кнопке) 

Рекомендации (сейчас делать этого не нужно): 
Все компоненты из ui-kit должны принимать ref ( React.forwardRef поможет). (Кстати если бы ты так сделал, то не пришлось бы оборачивать все компоненты с помощью Controller для работы с RHF)

2024-02-06 22:29 UTC, Dtroonn commented on src/components/Select/Select.tsx
> +    value: number;
Это делать сейчас не нужно, но на будущее , по - сути это должно быть дженериком т.к value прокидываемое сверху может быть любым

2024-02-06 22:29 UTC, Dtroonn commented on src/pages/CategoriesPage/CategoriesPage.tsx
> +            <Header buttonText='Добавить категорию' onButtonClick={addCategoryHandler}/>
Правильнее будет сделать, чтобы твой хэдер имел слот, в который можно прокинуть "фичу"  - в твоем случае создание категории/таски. Твоя фича это кнопка, в которой логика по открытию/закрытию модалки и сама модалка. А то у тебя сейчас ререндерится всё что написано здесь при открытии/закрытии модалки, что отрицательно сказывается на перфомансе приложения

2024-02-06 22:29 UTC, Dtroonn commented on src/components/DeleteTaskModal/DeleteTaskModal.tsx
> +    const onCloseHandler = useCallback(() => {
Ненужный useCallback он только вредит перфомансу приложения и это не единственный в проекте. Почему так, можем обсудить в лс/на созвоне так же можешь посмотреть след. видео: https://www.youtube.com/watch?v=2Wp7QPTkpms&ab_channel=%D0%90%D0%B9%D0%A2%D0%B8%D0%A1%D0%B8%D0%BD%D1%8F%D0%BA

2024-02-06 22:29 UTC, Dtroonn commented on src/constants/constants.ts
> +} as ICategory
Они тебе больше не нужны, ты же сделал, что формы принимают опционально дефолтные значения

2024-02-06 22:29 UTC, Dtroonn commented on src/components/TaskModal/TaskModal.tsx
> +const selectOptions = createSelector(
Должен быть в доменной зоне у категорий с остальными селекторами т.е селекторы внутри компонента обычно не пишут т.к одна из их сути - переиспользование, да и вообще выглядит странно

2024-02-06 22:29 UTC, Dtroonn commented on src/ui-kit/Button/Button.tsx
> +const Button:FC<PropsWithChildren<ButtonProps>> = ({
У кнопки нет пропа loading, который дизейблит кнопку и показывает загрузку + не обработан момент с показом, что таска/категория создается/редактируется => плохой ux (кнопка и этот момент связаны)

2024-02-07 17:49 UTC, Dtroonn approved these changes

2024-02-07 17:49 UTC, Dtroonn commented on src/ui-kit/OverlayingPopup/OverlayingPopup.tsx
> +    }
По сути так быть не должно т.к если бы у тебя была бы анимация закрытия, то она бы таким образом не отобразилась

2024-02-07 17:49 UTC, Dtroonn commented on src/components/Category/Category.tsx
> +            />
Заметь, что щас это в принципе нормально т.к у тебя при закрытии popup возвращает null. Если бы так не было и VDOM от попапа оставался , то пришлось бы выносить на уровень выше т.к был бы создан VDOM разметки модалок на каждый компонент категории. Но вообще у тебя и так сейчас остаются жить компоненты, точнее их тело, которое выполняется на каждый ререндер компонента категорий (а у тебя их может быть много), поэтому лучше вынести это все на уровень выше, а не рендерить в компоненте категории

2024-03-20 14:49 UTC, merged